### PR TITLE
Possible refactoring of DidPlayerWinRPS method

### PR DESCRIPTION
**Pull request by Zeus2459**

### CODE REVIEW

**Comment by exsersewo** [comment]
Ran these changed in a dotnet fiddle environment and got illegal results back from the method

Code Snippet:
```cs
for(int player = 0; player < 3; player++)
{
            for(int skuld = 0; skuld < 3; skuld++)
	    {
                 Console.WriteLine(player.ToString() + " , " + skuld.ToString() + " = " + CheckWin(player, skuld).ToString());
	     }
}

public static int CheckWin(int userThrow, int skuldThrow)
{
        return (userThrow - skuldThrow) + 2 % 3;
}
```

Results in:
```
0 , 0 = 2
0 , 1 = 1
0 , 2 = 0
1 , 0 = 3
1 , 1 = 2
1 , 2 = 1
2 , 0 = 4
2 , 1 = 3
2 , 2 = 2
```

Due to this (unless it can be remedied) this pull request will not be merged.

**Comment by Zeus2459** [comment]
`return (userThrow - skuldThrow) + 2 % 3;`
should be
`return (userThrow - skuldThrow + 2) % 3;`

**Comment by exsersewo** [comment]
MB mobile testing 😅

**Comment by Multivax** [comment]
odd man

**Pull request merged**
